#!/bin/bash
# Install the market-open uptime check (05-Aug, automation item #1).
#
# WHY THIS SHAPE: the engine can page about anything EXCEPT its own absence —
# the not-running check must live outside the process, which means launchd.
# But macOS TCC denies launchd agents access to ~/Documents, where this repo
# lives — so the installed check script is COPIED to ~/.tradewell/ (outside
# TCC's fence) with the ntfy URL baked in at install time, and at runtime it
# touches nothing but localhost:8000 and the webhook. Re-run this script any
# time .env's ALERT_WEBHOOK_URL changes; it is idempotent.
#
# Schedule: 09:10 and 09:25 IST, Monday-Friday (this Mac runs IST). Two shots
# so a slow morning start gets one nudge, not a storm. NSE holidays are not
# known to launchd — the page says so.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_DIR/backend/.env"
DEST_DIR="$HOME/.tradewell"
CHECK="$DEST_DIR/uptime_check.sh"
PLIST="$HOME/Library/LaunchAgents/com.tradewell.uptime.plist"
LABEL="com.tradewell.uptime"

if [ ! -f "$ENV_FILE" ]; then
  echo "ERROR: $ENV_FILE not found — run from the Tradewell repo." >&2
  exit 1
fi
# The PRIMARY topic only: an uptime page describes your infrastructure and
# must never reach the shared signals topic.
WEBHOOK="$(grep -E '^ALERT_WEBHOOK_URL=' "$ENV_FILE" | head -1 | cut -d= -f2- | tr -d ' ')"
if [ -z "$WEBHOOK" ]; then
  echo "ERROR: ALERT_WEBHOOK_URL is empty in backend/.env — nothing to page." >&2
  exit 1
fi

mkdir -p "$DEST_DIR"
cat > "$CHECK" <<EOF
#!/bin/bash
# Generated by install_uptime_check.sh — do not edit; re-run the installer.
# Pages the private ntfy topic if the Tradewell backend is not answering at
# market open. Runs from launchd OUTSIDE ~/Documents (TCC), touches only
# localhost and the webhook.
if ! curl -sf -m 5 http://localhost:8000/health >/dev/null 2>&1; then
  curl -s -m 8 \\
    -H "Title: TRADEWELL NOT RUNNING at market open" \\
    -d "No response from localhost:8000 — the engine is missing today's session (and today's evidence). Start it: cd Tradewell && ./start.sh. Ignore if NSE holiday." \\
    "$WEBHOOK" >/dev/null 2>&1
fi
EOF
chmod 700 "$CHECK"

cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array><string>/bin/bash</string><string>$CHECK</string></array>
  <key>StartCalendarInterval</key>
  <array>
$(for wd in 1 2 3 4 5; do for t in "9 10" "9 25"; do
    set -- $t
    printf '    <dict><key>Weekday</key><integer>%s</integer><key>Hour</key><integer>%s</integer><key>Minute</key><integer>%s</integer></dict>\n' "$wd" "$1" "$2"
  done; done)
  </array>
</dict>
</plist>
EOF

launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"
echo "Installed: $LABEL — checks localhost:8000 at 09:10 and 09:25 IST, Mon-Fri."
echo "Check script: $CHECK (webhook baked in; re-run installer after rotating the topic)."
echo "Test now with:  launchctl start $LABEL   (pages only if the backend is DOWN)"
